services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=book-store
      - POSTGRES_PASSWORD=book-store
      - POSTGRES_DB=book-store
    networks:
      - my_network

  elasticsearch:
    image: elasticsearch:7.17.23
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true
      - cluster.name=docker-cluster
      - ELASTIC_PASSWORD=nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -u elastic:nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9 -f http://localhost:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - my_network

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.17.23
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -f http://localhost:5601/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "5601:5601"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - my_network

volumes:
  elastic_data:

networks:
  my_network:
